export const company = {
  name: 'LABEL PRO CI',
  slogan: 'Nous construisons les infrastructures qui façonnent l\'avenir.',
  description: 'LABEL PRO CI est une entreprise ivoirienne spécialisée dans les travaux de BTP, le génie civil et les infrastructures. Basée à Yamoussoukro, l\'entreprise accompagne les particuliers, les entreprises et les institutions dans la réalisation de projets de construction, de rénovation et d\'aménagement avec un engagement constant envers la qualité, la sécurité et le respect des délais.',
  shortDescription: 'Entreprise ivoirienne spécialisée en BTP et Génie Civil. Des projets réalisés avec rigueur, expertise et excellence.',

  contact: {
    phone: '+225 27 35 96 63 27',
    phoneSecondary: '+225 07 88 51 21 75',
    phoneClean: '+2252735966327',
    phoneSecondaryClean: '+2250788512175',
    whatsapp: '+2250788512175',
    whatsappClean: '2250788512175',
    email: 'contact@labelproci.com',
    address: 'Yamoussoukro, Côte d\'Ivoire',
    fullAddress: 'Quartier Commerce, Yamoussoukro, Côte d\'Ivoire',
    gps: { lat: 6.8276, lng: -5.2893 },
  },

  hours: {
    weekdays: 'Lundi - Vendredi : 07h30 - 18h00',
    saturday: 'Samedi : 08h00 - 13h00',
    sunday: 'Dimanche : Fermé',
  },

  social: {
    facebook: 'https://facebook.com/labelproci',
    linkedin: 'https://linkedin.com/company/labelproci',
    instagram: 'https://instagram.com/labelproci',
    youtube: 'https://youtube.com/@labelproci',
  },

  stats: {
    projects: 150,
    clients: 120,
    years: 12,
    satisfaction: 98,
  },

  zones: [
    'Yamoussoukro',
    'Abidjan',
    'Bouaké',
    'Daloa',
    'San-Pédro',
    'Korhogo',
    'Toute la Côte d\'Ivoire',
  ],

  services: [
    {
      id: 'construction-batiments',
      title: 'Construction de Bâtiments',
      shortDesc: 'Construction de bâtiments résidentiels, commerciaux et industriels avec des normes de qualité internationales.',
      description: 'LABEL PRO CI réalise la construction de bâtiments résidentiels, commerciaux et industriels. Notre équipe d\'ingénieurs et d\'architectes garantit des ouvrages conformes aux normes de qualité les plus exigeantes, livrés dans les délais convenus.',
      icon: 'Building2',
      advantages: [
        'Respect strict des normes de construction',
        'Matériaux certifiés et de haute qualité',
        'Équipe d\'ingénieurs qualifiés',
        'Suivi de chantier rigoureux',
        'Livraison dans les délais',
        'Garantie décennale',
      ],
      methodology: [
        'Étude de faisabilité et analyse du terrain',
        'Conception architecturale et plans techniques',
        'Obtention des autorisations administratives',
        'Terrassement et fondations',
        'Construction du gros œuvre',
        'Second œuvre et finitions',
        'Réception et livraison',
      ],
    },
    {
      id: 'genie-civil',
      title: 'Génie Civil',
      shortDesc: 'Ouvrages d\'art, ponts, ouvrages hydrauliques et infrastructures complexes réalisés avec expertise.',
      description: 'Notre division Génie Civil conçoit et réalise des ouvrages d\'art d\'envergure : ponts, dalots, ouvrages hydrauliques et infrastructures complexes. Nous mobilisons des équipements lourds et une expertise technique pointue pour chaque projet.',
      icon: 'Landmark',
      advantages: [
        'Expertise en ouvrages d\'art',
        'Équipements lourds performants',
        'Calculs et dimensionnement précis',
        'Respect des normes de sécurité',
        'Expérience sur projets complexes',
        'Contrôle qualité permanent',
      ],
      methodology: [
        'Études géotechniques et topographiques',
        'Conception et dimensionnement',
        'Mobilisation des équipements',
        'Travaux de fondation',
        'Réalisation de l\'ouvrage',
        'Contrôle et essais',
        'Réception des travaux',
      ],
    },
    {
      id: 'travaux-publics',
      title: 'Travaux Publics',
      shortDesc: 'Routes, autoroutes, pistes rurales et infrastructures de transport pour le développement national.',
      description: 'LABEL PRO CI intervient sur des projets de travaux publics d\'envergure : construction de routes, autoroutes, pistes rurales et aménagements urbains. Nous contribuons activement au développement des infrastructures de transport en Côte d\'Ivoire.',
      icon: 'Route',
      advantages: [
        'Maîtrise des techniques routières',
        'Parc d\'engins adapté',
        'Expérience sur chantiers nationaux',
        'Respect des délais contractuels',
        'Contrôle qualité des matériaux',
        'Sécurité sur chantier',
      ],
      methodology: [
        'Études topographiques et géotechniques',
        'Défrichement et déboisement',
        'Terrassement et compactage',
        'Pose de couches de base et de surface',
        'Signalisation et aménagements',
        'Réception provisoire',
        'Réception définitive',
      ],
    },
    {
      id: 'vrd',
      title: 'VRD - Voirie et Réseaux Divers',
      shortDesc: 'Voirie, réseaux d\'assainissement, adduction d\'eau et réseaux électriques pour lotissements.',
      description: 'Notre expertise en VRD couvre la réalisation de voiries, réseaux d\'assainissement, adduction d\'eau et réseaux électriques pour les lotissements et zones d\'habitat. Nous assurons l\'ensemble des réseaux nécessaires au bon fonctionnement des infrastructures urbaines.',
      icon: 'Network',
      advantages: [
        'Vision globale des réseaux',
        'Coordination multi-corps de métier',
        'Respect des normes techniques',
        'Intégration environnementale',
        'Livraison clé en main',
        'Maintenance préventive',
      ],
      methodology: [
        'Études techniques et hydrauliques',
        'Plan de masse des réseaux',
        'Terrassement et tranchées',
        'Pose des canalisations',
        'Raccordements et branchements',
        'Revêtement de voirie',
        'Essais et réception',
      ],
    },
    {
      id: 'terrassement',
      title: 'Terrassement',
      shortDesc: 'Préparation de terrains, nivellement, remblais et déblais avec des engins performants.',
      description: 'LABEL PRO CI dispose d\'un parc d\'engins performants pour tous types de terrassement : préparation de terrain, nivellement, remblais, déblais et compactage. Notre expertise garantit des fondations solides pour vos projets de construction.',
      icon: 'Tractor',
      advantages: [
        'Parc d\'engins modernes',
        'Opérateurs expérimentés',
        'Capacité de production élevée',
        'Compactage contrôlé',
        'Gestion des déblais',
        'Respect des profils',
      ],
      methodology: [
        'Reconnaissance du terrain',
        'Décapage de la terre végétale',
        'Déblais et remblais',
        'Compactage par couches',
        'Nivellement et profilage',
        'Contrôle de compacité',
        'Réception des terrassements',
      ],
    },
    {
      id: 'assainissement',
      title: 'Assainissement',
      shortDesc: 'Réseaux d\'assainissement, stations d\'épuration et systèmes de drainage pour un environnement sain.',
      description: 'Notre division Assainissement conçoit et réalise des réseaux d\'évacuation des eaux usées et pluviales, des stations d\'épuration et des systèmes de drainage. Nous contribuons à la protection de l\'environnement et à la salubrité des espaces urbains.',
      icon: 'Droplets',
      advantages: [
        'Expertise en hydrologie',
        'Solutions durables',
        'Respect des normes environnementales',
        'Techniques modernes',
        'Maintenance prévue',
        'Conformité réglementaire',
      ],
      methodology: [
        'Études hydrologiques',
        'Dimensionnement des réseaux',
        'Travaux de terrassement',
        'Pose des canalisations',
        'Construction des ouvrages',
        'Essais d\'étanchéité',
        'Mise en service',
      ],
    },
    {
      id: 'rehabilitation',
      title: 'Réhabilitation et Rénovation',
      shortDesc: 'Remise à neuf de bâtiments existants, renforcement structurel et modernisation des infrastructures.',
      description: 'LABEL PRO CI intervient dans la réhabilitation et la rénovation de bâtiments existants. Notre approche combine expertise technique et respect du patrimoine pour donner une seconde vie à vos constructions tout en améliorant leur performance.',
      icon: 'RefreshCw',
      advantages: [
        'Diagnostic approfondi',
        'Solutions adaptées',
        'Respect du patrimoine',
        'Techniques de pointe',
        'Minimisation des nuisances',
        'Garantie sur les travaux',
      ],
      methodology: [
        'Diagnostic technique complet',
        'Étude de solutions',
        'Proposition financière',
        'Travaux de démolition sélective',
        'Renforcement structurel',
        'Finitions et modernisation',
        'Réception des travaux',
      ],
    },
    {
      id: 'etudes-techniques',
      title: 'Études Techniques',
      shortDesc: 'Études de faisabilité, conception, calculs de structure et ingénierie de projet.',
      description: 'Notre bureau d\'études réalise toutes les études techniques nécessaires à vos projets : études de faisabilité, conception architecturale, calculs de structure, métré et estimation des coûts. Une ingénierie rigoureuse pour des projets réussis.',
      icon: 'ClipboardList',
      advantages: [
        'Bureau d\'études intégré',
        'Logiciels de calcul modernes',
        'Équipe pluridisciplinaire',
        'Études détaillées',
        'Optimisation des coûts',
        'Conformité réglementaire',
      ],
      methodology: [
        'Recueil des besoins',
        'Études préliminaires',
        'Conception et calculs',
        'Rédaction des CCTP',
        'Métré et estimation',
        'Dossier d\'exécution',
        'Assistance technique',
      ],
    },
  ],

  values: [
    { title: 'Excellence', description: 'Nous visons l\'excellence dans chaque projet, avec des standards de qualité internationaux.' },
    { title: 'Intégrité', description: 'Nous agissons avec honnêteté et transparence dans toutes nos relations professionnelles.' },
    { title: 'Sécurité', description: 'La sécurité de nos équipes et de nos ouvrages est notre priorité absolue.' },
    { title: 'Innovation', description: 'Nous intégrons les dernières technologies et méthodes de construction.' },
    { title: 'Satisfaction Client', description: 'Le succès de nos clients est la mesure de notre propre réussite.' },
  ],

  whyUs: [
    { title: 'Respect des Délais', description: 'Nous nous engageons sur des calendriers réalistes et les respectons scrupuleusement.', icon: 'Clock' },
    { title: 'Équipe Qualifiée', description: 'Nos ingénieurs et techniciens sont formés aux meilleures pratiques du secteur.', icon: 'Users' },
    { title: 'Matériaux Certifiés', description: 'Nous utilisons exclusivement des matériaux certifiés et de haute qualité.', icon: 'Shield' },
    { title: 'Gestion Rigoureuse', description: 'Chaque projet bénéficie d\'un suivi méthodique et d\'un contrôle qualité permanent.', icon: 'CheckCircle' },
    { title: 'Suivi Personnalisé', description: 'Un chef de projet dédié vous accompagne de la conception à la livraison.', icon: 'UserCheck' },
    { title: 'Garantie Qualité', description: 'Tous nos ouvrages sont couverts par une garantie et un service après-vente réactif.', icon: 'Award' },
  ],

  process: [
    { step: 1, title: 'Prise de Contact', description: 'Échangez avec notre équipe pour définir votre projet et vos besoins.' },
    { step: 2, title: 'Étude Technique', description: 'Nos ingénieurs analysent la faisabilité et conçoivent les plans détaillés.' },
    { step: 3, title: 'Devis Détaillé', description: 'Nous vous fournissons un devis transparent et détaillé.' },
    { step: 4, title: 'Réalisation', description: 'Notre équipe exécute les travaux avec rigueur et professionnalisme.' },
    { step: 5, title: 'Livraison', description: 'Réception des travaux, remise des garanties et suivi post-livraison.' },
  ],

  testimonials: [
    {
      name: 'M. Koné Aboubacar',
      role: 'Promoteur Immobilier',
      content: 'LABEL PRO CI a réalisé la construction de notre immeuble de bureaux à Yamoussoukro. La qualité des travaux et le respect des délais ont été exemplaires. Je recommande vivement cette entreprise.',
      rating: 5,
    },
    {
      name: 'Mme Touré Awa',
      role: 'Directrice Générale',
      content: 'Un partenaire de confiance pour nos projets de construction. L\'équipe de LABEL PRO CI est professionnelle, réactive et à l\'écoute. La qualité de leurs finitions est remarquable.',
      rating: 5,
    },
    {
      name: 'M. Diarra Sékou',
      role: 'Maître d\'Ouvrage',
      content: 'Nous avons fait appel à LABEL PRO CI pour la réhabilitation de notre bâtiment administratif. Le résultat est à la hauteur de nos attentes. Excellent rapport qualité-prix.',
      rating: 5,
    },
    {
      name: 'M. Bamba Idriss',
      role: 'Architecte',
      content: 'En tant qu\'architecte, je suis très satisfait de la collaboration avec LABEL PRO CI. Ils comprennent parfaitement les exigences techniques et livrent des ouvrages de grande qualité.',
      rating: 5,
    },
  ],

  projects: [
    {
      id: 1,
      title: 'Immeuble de Bureaux Moderne',
      category: 'Construction',
      location: 'Yamoussoukro',
      duration: '14 mois',
      description: 'Construction d\'un immeuble de bureaux de 5 étages avec parking souterrain, espaces commerciaux et terrasses végétalisées.',
      year: 2024,
    },
    {
      id: 2,
      title: 'Route Nationale RN4',
      category: 'Travaux Publics',
      location: 'Yamoussoukro - Bouaké',
      duration: '24 mois',
      description: 'Réhabilitation et élargissement de 45 km de route nationale avec aménagement des intersections et signalisation.',
      year: 2023,
    },
    {
      id: 3,
      title: 'Lotissement Résidentiel',
      category: 'VRD',
      location: 'Yamoussoukro',
      duration: '18 mois',
      description: 'Aménagement d\'un lotissement de 50 parcelles avec voirie, assainissement, adduction d\'eau et éclairage public.',
      year: 2024,
    },
    {
      id: 4,
      title: 'Pont sur la Comoé',
      category: 'Génie Civil',
      location: 'Abidjan',
      duration: '30 mois',
      description: 'Construction d\'un pont à poutres précontraintes de 120 mètres avec voies de circulation et trottoirs.',
      year: 2023,
    },
    {
      id: 5,
      title: 'Centre Commercial',
      category: 'Construction',
      location: 'Abidjan',
      duration: '20 mois',
      description: 'Construction d\'un centre commercial de 8000 m² avec parking, espaces de restauration et cinémas.',
      year: 2024,
    },
    {
      id: 6,
      title: 'Station d\'Épuration',
      category: 'Assainissement',
      location: 'Bouaké',
      duration: '16 mois',
      description: 'Construction d\'une station d\'épuration des eaux usées d\'une capacité de 10 000 m³/jour.',
      year: 2023,
    },
    {
      id: 7,
      title: 'Terrassement Zone Industrielle',
      category: 'Terrassement',
      location: 'San-Pédro',
      duration: '12 mois',
      description: 'Terrassement et préparation de 25 hectares pour une zone industrielle avec drainage et viabilisation.',
      year: 2024,
    },
    {
      id: 8,
      title: 'Rénovation Hôtel 5 Étoiles',
      category: 'Réhabilitation',
      location: 'Yamoussoukro',
      duration: '10 mois',
      description: 'Rénovation complète d\'un hôtel 5 étoiles avec mise aux normes, modernisation des équipements et redesign intérieur.',
      year: 2024,
    },
  ],

  blogCategories: ['Construction', 'Génie Civil', 'BTP', 'Conseils', 'Innovations'],

  blogPosts: [
    {
      id: 1,
      title: 'Les tendances de la construction durable en Côte d\'Ivoire',
      category: 'Construction',
      excerpt: 'Découvrez comment les entreprises ivoiriennes intègrent les principes de développement durable dans leurs projets de construction.',
      date: '2024-12-15',
      readTime: '5 min',
    },
    {
      id: 2,
      title: 'L\'importance des études géotechniques avant construction',
      category: 'Génie Civil',
      excerpt: 'Pourquoi chaque projet de construction doit commencer par une étude de sol approfondie et comment cela évite des problèmes futurs.',
      date: '2024-11-28',
      readTime: '4 min',
    },
    {
      id: 3,
      title: 'Guide complet : Comment choisir son entreprise de BTP',
      category: 'Conseils',
      excerpt: 'Les critères essentiels pour sélectionner une entreprise de construction fiable et compétente pour votre projet.',
      date: '2024-11-10',
      readTime: '6 min',
    },
    {
      id: 4,
      title: 'Innovation : Les nouvelles techniques de terrassement',
      category: 'Innovations',
      excerpt: 'Comment les technologies modernes révolutionnent les techniques de terrassement et améliorent l\'efficacité des chantiers.',
      date: '2024-10-22',
      readTime: '5 min',
    },
  ],

  seo: {
    title: 'LABEL PRO CI - Entreprise BTP & Génie Civil à Yamoussoukro',
    description: 'LABEL PRO CI, entreprise ivoirienne spécialisée en BTP, génie civil, construction et travaux publics à Yamoussoukro. Demandez votre devis gratuit.',
    keywords: [
      'BTP Côte d\'Ivoire',
      'Génie Civil Yamoussoukro',
      'Construction Côte d\'Ivoire',
      'Entreprise BTP Yamoussoukro',
      'Travaux publics Côte d\'Ivoire',
      'Entreprise de construction Côte d\'Ivoire',
      'Devis BTP Côte d\'Ivoire',
      'VRD Yamoussoukro',
      'Terrassement Côte d\'Ivoire',
      'Assainissement Yamoussoukro',
    ],
  },
};

export type Service = typeof company.services[number];
export type Project = typeof company.projects[number];
export type Testimonial = typeof company.testimonials[number];
export type BlogPost = typeof company.blogPosts[number];
